### ISSUE TITLE
Complete Remaining User Space Application Functions

### ISSUE THREAD

**Issue by geoffreyjensen6** [geoffreyjensen6/final-project-spice-rack-app#1]
**Task:** Need to complete the remaining functions and features needed for the user space application. 

- [x] Add function to read calibration data out of storage file and into struct
- [x] Add locking with Mutex in locations where access to data structure is needed.
- [x] Add function to use calibration data to convert ADC readings into mass (grams) 
- [x] User space function to lookup and convert each spice from grams to tsp. Each spice will be different here so will require some file I/O and lookup.
- [x] User space app needs to be checking for when a spice is removed so it can log the ADC reading for when it is placed back on and accurately calculated the new mass of the spice

**DoD:** User space app runs at startup and has a log of all spice amounts available. When a spice is removed, the applications will adjust the amounts available when the spice is placed back on the rack. 

**Blockers:** None

**Status:** This issue is complete at as of 6/22/2023 with commit and https://github.com/geoffreyjensen6/final-project-spice-rack-app/commit/03d44419e23b248fcde1824cca7fb3c029607b0c of [final-project-spice-rack-app](https://github.com/geoffreyjensen6/final-project-spice-rack-app), [`7490e66`](https://github.com/cu-ecen-aeld/final-project-geoffreyjensen6/commit/7490e66987490817434b3a83798f0dd4e53b0ca7) repo [final-project-geoffreyjensen6](https://github.com/cu-ecen-aeld/final-project-geoffreyjensen6), and [`74a8658`](https://github.com/geoffreyjensen6/final-project-fsr-driver/commit/74a8658abb816f35c765cd38ffa4f61ec8254b67)of [final-project-fsr-driver](https://github.com/geoffreyjensen6/final-project-fsr-driver). DoD has been verified. With these releases you are able to successfully build the package in buildroot and load it on the Beaglebone Black. The package was developed so that if the calibration data file is found, the application can run as a daemon at startup and continually updates the spice levels when spices are removed and put back. If the calibration data is not found, a message is printed to log at startup that indicates to user they need to launch manually to perform calibration routine first because this requires user input and interaction.

The picture below shows the scenario you would exhibit in most cases. The initial setup/calibration has been done so when you bring up the beaglebone and boot Linux, the application detects the calibration data and starts the application as a Daemon. In the example below, you see that I remove Garlic Powder which is in the Spice2 location. I then put the jar back moments later and it logs both instances and collects new readings. As you can see it is very similar but there is some variability in the ADC readings so it will change. I display the contents of the spice_rack_consolidated.txt file which is the file that is continually updated and transmitted over the TCP socket.

![Image](https://github.com/geoffreyjensen6/final-project-spice-rack-app/assets/123145400/3b891960-4f90-462f-b8f1-662ebaeb989c)

The picture below shows the scenario where you boot up for the first time and the calibration data file is not present. In this case it cannot launch the application as a Daemon because user input and interaction is required so you must launch like it specifies. Once you do this it automatically walks through the calibration routine and begins running after that. Once application is running, I sent a request from my linux development machine to query the spices. It sends over TCP socket and also prints out to console what it is sending.

![Image](https://github.com/geoffreyjensen6/final-project-spice-rack-app/assets/123145400/4226fb50-aaf8-430d-adb6-8b053f7cd624)

This is a 3rd scenario I wanted to highlight. It is the use case where you want to perform calibration again. You can either delete the calibration file and it would do this automatically on next boot, or if you are running the application manually from /usr/bin/spice_rack/spice_rack_app, you can just press the calibration button and it will initiate the routine for you. As you can see here it does this.

![Image](https://github.com/geoffreyjensen6/final-project-spice-rack-app/assets/123145400/337c30ad-fb43-4115-8f5e-128e295cb98f)

**Comment by geoffreyjensen6** [comment]
**Status:** This issue is complete at as of 6/22/2023 with commit  and 03d4441 of [final-project-spice-rack-app](https://github.com/geoffreyjensen6/final-project-spice-rack-app), [`7490e66`](https://github.com/cu-ecen-aeld/final-project-geoffreyjensen6/commit/7490e66987490817434b3a83798f0dd4e53b0ca7) repo [final-project-geoffreyjensen6](https://github.com/cu-ecen-aeld/final-project-geoffreyjensen6), and [`74a8658` ](https://github.com/geoffreyjensen6/final-project-fsr-driver/commit/74a8658abb816f35c765cd38ffa4f61ec8254b67) of [final-project-fsr-driver](https://github.com/geoffreyjensen6/final-project-fsr-driver). DoD has been verified. With these releases you are able to successfully build the package in buildroot and load it on the Beaglebone Black. The package was developed so that if the calibration data file is found, the application can run as a daemon at startup and continually updates the spice levels when spices are removed and put back. If the calibration data is not found, a message is printed to log at startup that indicates to user they need to launch manually to perform calibration routine first because this requires user input and interaction. 

The picture below shows the scenario you would exhibit in most cases. The initial setup/calibration has been done so when you bring up the beaglebone and boot Linux, the application detects the calibration data and starts the application as a Daemon. In the example below, you see that I remove Garlic Powder which is in the Spice2 location. I then put the jar back moments later and it logs both instances and collects new readings. As you can see it is very similar but there is some variability in the ADC readings so it will change. I display the contents of the spice_rack_consolidated.txt file which is the file that is continually updated and transmitted over the TCP socket.


![Image](https://github.com/geoffreyjensen6/final-project-spice-rack-app/assets/123145400/a2bbac5d-1e29-4e5e-9b7e-b463bb46397e)


The picture below shows the scenario where you boot up for the first time and the calibration data file is not present. In this case it cannot launch the application as a Daemon because user input and interaction is required so you must launch like it specifies. Once you do this it automatically walks through the calibration routine and begins running after that. Once application is running, I sent a request from my linux development machine to query the spices. It sends over TCP socket and also prints out to console what it is sending.



![Image](https://github.com/geoffreyjensen6/final-project-spice-rack-app/assets/123145400/72136ce3-3fb7-4111-8426-e624168eeb56)



This is a 3rd scenario I wanted to highlight. It is the use case where you want to perform calibration again. You can either delete the calibration file and it would do this automatically on next boot, or if you are running the application manually from /usr/bin/spice_rack/spice_rack_app, you can just press the calibration button and it will initiate the routine for you. As you can see here it does this.



![Image](https://github.com/geoffreyjensen6/final-project-spice-rack-app/assets/123145400/7dfe517a-1510-40f7-969b-74360f39c5cc)

This sprint proved to be very challenging in the beginning. I initially started with working on adding a couple more parameters to the output storage file structure because I knew I would need them. As soon as I added a couple more parameters (Grams, teaspoons) to the output calibration file, I found myself hitting some segmentation faults while trying to free from the storage function. I ended up adding GDB to my buildroot config and even Valgrind to try and debug the issues. It was not easy to narrow down the issue though and eventually it led me to redesigning some of the functions such as the storage one. The new implementation relies more on file I/O and not as much on storing all the data in memory temporarily (data structs were getting large with previous implementation). It is a much cleaner implementation now but did require a fair amount of time to debug all this and then rewrite some of the work I did in Sprint 2.

After I added the new parameters of grams and tsp to the output storage file structure, I then wrote functions to perform conversions from the ADC readings to grams and another function to convert from grams to tsps. The ADC readings to grams function relies on the calibration data. It uses the empty jar reading and empty rack reading along with the known mass of the empty jar to help determine the scaling factor of the ADC readings. Then it just uses scaling factor along with offset(adc measurement before a new jar is added) to calculate the mass. In order to get the empty jar and empty rack adc readings though I needed to access what I stored to the calibration file so I did have to  add a function to read stuff out of the calibration file into struct. This required reading the output storage file and creating a parsing function. I decided to make it more of a csv output file as I figured that would be simple to parse. Reading the file in and parsing wasn't too bad, however I was trying to make this struct fairly dynamic with the intent that it was easy to make the spice rack scale to more spices later. I implemented it so that the spice structure was a flexible array member of the spice rack struct. That way more could be added. I also had tried to make the output storage parameter fields flexible arrays and this is where I got into trouble. It ended up causing some issues for me so I reverted back to just having the spices as the flexible array members of the struct. It didn't seem to like having nested structs and the different tiers having flexible array members. After I finished reading the parameters in I could move back to the conversion functions. I did some comparison to a household kitchen scale after I wrote the ADC reading to grams function, and it is within 1g of accuracy.  After getting the mass piece figured out, I now could use those numbers to convert to teaspoons which was really the goal because most recipes call out for teaspoons or tablespoons of spices. I choose teaspoons because it is a more precise unit and conversion to tablespoons is easy (1tbsp = 3tsp). This part was a little more tricky because all spices have different a different mass and so conversion requires this conversion factor be known about the spices. I found a good table online that showed the conversion for most household spices. I saved the data to a .csv and wrote a function in the application that parses this file and pulls this information in to check against which spice the user enters during the calibration routine. These two big pieces involved a lot of file I/O (reading, writing, seeking). 

Next I moved on to how I wanted to check for whether a spice was removed or added back. I considered modifying the fsr driver to enable interrupts or something like that but in the end I decided to use a timer configuration where the application goes out and checks the fsr status routinely for a change. Then I implemented a mutex lock in the thread struct between the timer thread and main application so that I can alter a variable to indicate to the main application that the status changed and it should go address it and flip that variable back. 

The application was running pretty well after all this, but I still had some key stuff to implement like the calibration button monitoring. I ended up launching a new thread for the application to monitor the calibration button status and if it found a change, it kicks off the calibration routine. This required threading and more Mutex lock work. I also added signal handler like we did in a previous assignment  to ensure it performs a clean exit if user kills program. I hadn't been doing this earlier and it was always giving me an error about not being able to export /sys/class gpio file because it was already done.

Lastly when I initially defined this Sprint, I just assumed I wanted to run in background on bootup because if power went out or something like that, I wouldn't want to have to hook up to a computer to relaunch every time (since the intent is for the spice rack to be in the kitchen this would be very annoying to do). However it was difficult with the calibration routine requiring human interaction. Although ideally calibration is only performed on the initial setup of the device and then it references that data going forward. So I decided just to put a message out to console if it cannot find application data and to not even launch application if it cannot. If it does find it then I launch the application as a daemon (no messages to terminal when using ssh, but you do see the print statements if connected via serial console).
